633: Support for redirect binding signature check using query param v…
IdentityPython/pysaml2 pull request #805
Opened 2021-05-18 22:00 UTC by vkadam

This is pull-request to fix issue number #633

### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you added an explanation of what problem you are trying to solve with this PR?
* [x] Have you added information on what your changes do and why you chose this as your solution?
* [x] Have you written new tests for your changes?
* [x] Does your submission pass tests?
* [x] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

2021-06-01 13:18 UTC, peppelinux requested changes

2021-06-01 16:20 UTC, vkadam commented on src/saml2/request.py
> +            # If redirect binding, and provided SigAlg, Signature use that to verify
Make sense about try/catch, just pushed refactored code, adjusted try/catch and made more readable (I think)

2021-07-01 16:27 UTC, vkadam commented
Any updates on this PR would be appreciated. Thanks in advance.

2021-11-02 11:49 UTC, c00kiemon5ter commented
hello everyone and thanks for the PR and your patience. I will try to review this ASAP and merge it in order to create the next pysaml2 release.

2021-11-16 13:03 UTC, c00kiemon5ter commented
Merged by 718cf98

2021-11-16 13:03 UTC, closed without merging